//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunScape.Locales {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SunScape.Locales.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2fa has been disabled. You can reenable 2fa when you setup an authenticator app.
        /// </summary>
        public static string _2fa_has_been_disabled__You_can_reenable_2fa_when_you_setup_an_authenticator_app {
            get {
                return ResourceManager.GetString("2fa has been disabled. You can reenable 2fa when you setup an authenticator app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à for.
        /// </summary>
        public static string _for {
            get {
                return ResourceManager.GetString("for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {Name} logged in with {LoginProvider} provider..
        /// </summary>
        public static string _Name__logged_in_with__LoginProvider__provider_ {
            get {
                return ResourceManager.GetString("{Name} logged in with {LoginProvider} provider.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a local account so you can log in without an external login..
        /// </summary>
        public static string Add_a_local_account_so_you_can_log_in_without_an_external_login_ {
            get {
                return ResourceManager.GetString("Add a local account so you can log in without an external login.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add another provider to log in..
        /// </summary>
        public static string Add_another_provider_to_log_in_ {
            get {
                return ResourceManager.GetString("Add another provider to log in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add authenticator app.
        /// </summary>
        public static string Add_authenticator_app {
            get {
                return ResourceManager.GetString("Add authenticator app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Associate your {0} account..
        /// </summary>
        public static string Associate_your__0__account_ {
            get {
                return ResourceManager.GetString("Associate your {0} account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authenticator code.
        /// </summary>
        public static string Authenticator_code {
            get {
                return ResourceManager.GetString("Authenticator code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à before you can log in with a recovery code..
        /// </summary>
        public static string before_you_can_log_in_with_a_recovery_code_ {
            get {
                return ResourceManager.GetString("before you can log in with a recovery code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change email.
        /// </summary>
        public static string Change_email {
            get {
                return ResourceManager.GetString("Change email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to confirm your account.
        /// </summary>
        public static string Click_here_to_confirm_your_account {
            get {
                return ResourceManager.GetString("Click here to confirm your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure authenticator app.
        /// </summary>
        public static string Configure_authenticator_app {
            get {
                return ResourceManager.GetString("Configure authenticator app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm email.
        /// </summary>
        public static string Confirm_email {
            get {
                return ResourceManager.GetString("Confirm email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm email change.
        /// </summary>
        public static string Confirm_email_change {
            get {
                return ResourceManager.GetString("Confirm email change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation link to change email sent. Please check your email..
        /// </summary>
        public static string Confirmation_link_to_change_email_sent__Please_check_your_email_ {
            get {
                return ResourceManager.GetString("Confirmation link to change email sent. Please check your email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new account..
        /// </summary>
        public static string Create_a_new_account_ {
            get {
                return ResourceManager.GetString("Create a new account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete data and close my account.
        /// </summary>
        public static string Delete_data_and_close_my_account {
            get {
                return ResourceManager.GetString("Delete data and close my account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Personal Data.
        /// </summary>
        public static string Delete_Personal_Data {
            get {
                return ResourceManager.GetString("Delete Personal Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Selected.
        /// </summary>
        public static string Delete_Selected {
            get {
                return ResourceManager.GetString("Delete Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string Deleting_this_data_will_permanently_remove_your_account__and_this_cannot_be_recovered_ {
            get {
                return ResourceManager.GetString("Deleting this data will permanently remove your account, and this cannot be recov" +
                        "ered.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable 2FA.
        /// </summary>
        public static string Disable_2FA {
            get {
                return ResourceManager.GetString("Disable 2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable two-factor authentication (2FA).
        /// </summary>
        public static string Disable_two_factor_authentication__2FA_ {
            get {
                return ResourceManager.GetString("Disable two-factor authentication (2FA)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabling 2FA does not change the keys used in authenticator apps..
        /// </summary>
        public static string Disabling_2FA_does_not_change_the_keys_used_in_authenticator_apps_ {
            get {
                return ResourceManager.GetString("Disabling 2FA does not change the keys used in authenticator apps.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t have access to your authenticator device? You can.
        /// </summary>
        public static string Don_t_have_access_to_your_authenticator_device__You_can {
            get {
                return ResourceManager.GetString("Don\'t have access to your authenticator device? You can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à enable QR code generation.
        /// </summary>
        public static string enable_QR_code_generation {
            get {
                return ResourceManager.GetString("enable QR code generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the code in the confirmation box below..
        /// </summary>
        public static string Enter_the_code_in_the_confirmation_box_below_ {
            get {
                return ResourceManager.GetString("Enter the code in the confirmation box below.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your email..
        /// </summary>
        public static string Enter_your_email_ {
            get {
                return ResourceManager.GetString("Enter your email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: Could not load external login info..
        /// </summary>
        public static string Error__Could_not_load_external_login_info_ {
            get {
                return ResourceManager.GetString("Error: Could not load external login info.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: Failed to set phone number..
        /// </summary>
        public static string Error__Failed_to_set_phone_number_ {
            get {
                return ResourceManager.GetString("Error: Failed to set phone number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: Invalid authenticator code..
        /// </summary>
        public static string Error__Invalid_authenticator_code_ {
            get {
                return ResourceManager.GetString("Error: Invalid authenticator code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: Invalid email change confirmation link..
        /// </summary>
        public static string Error__Invalid_email_change_confirmation_link_ {
            get {
                return ResourceManager.GetString("Error: Invalid email change confirmation link.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: Invalid recovery code entered..
        /// </summary>
        public static string Error__Invalid_recovery_code_entered_ {
            get {
                return ResourceManager.GetString("Error: Invalid recovery code entered.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: The external login was not added. External logins can only be associated with one account..
        /// </summary>
        public static string Error__The_external_login_was_not_added__External_logins_can_only_be_associated_with_one_account_ {
            get {
                return ResourceManager.GetString("Error: The external login was not added. External logins can only be associated w" +
                        "ith one account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: The external login was not removed..
        /// </summary>
        public static string Error__The_external_login_was_not_removed_ {
            get {
                return ResourceManager.GetString("Error: The external login was not removed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error changing email..
        /// </summary>
        public static string Error_changing_email_ {
            get {
                return ResourceManager.GetString("Error changing email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error changing user name..
        /// </summary>
        public static string Error_changing_user_name_ {
            get {
                return ResourceManager.GetString("Error changing user name.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error confirming your email.
        /// </summary>
        public static string Error_confirming_your_email {
            get {
                return ResourceManager.GetString("Error confirming your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error finding user for unspecified email.
        /// </summary>
        public static string Error_finding_user_for_unspecified_email {
            get {
                return ResourceManager.GetString("Error finding user for unspecified email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error from external provider: {0}.
        /// </summary>
        public static string Error_from_external_provider___0_ {
            get {
                return ResourceManager.GetString("Error from external provider: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading external login information..
        /// </summary>
        public static string Error_loading_external_login_information_ {
            get {
                return ResourceManager.GetString("Error loading external login information.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading user with ID {0}.
        /// </summary>
        public static string Error_loading_user_with_ID__0_ {
            get {
                return ResourceManager.GetString("Error loading user with ID {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à External Login.
        /// </summary>
        public static string External_Login {
            get {
                return ResourceManager.GetString("External Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forget this browser.
        /// </summary>
        public static string Forget_this_browser {
            get {
                return ResourceManager.GetString("Forget this browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgot password confirmation.
        /// </summary>
        public static string Forgot_password_confirmation {
            get {
                return ResourceManager.GetString("Forgot password confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgot your password?.
        /// </summary>
        public static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à generate a new set of recovery codes.
        /// </summary>
        public static string generate_a_new_set_of_recovery_codes {
            get {
                return ResourceManager.GetString("generate a new set of recovery codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Recovery Codes.
        /// </summary>
        public static string Generate_Recovery_Codes {
            get {
                return ResourceManager.GetString("Generate Recovery Codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate two-factor authentication (2FA) recovery codes.
        /// </summary>
        public static string Generate_two_factor_authentication__2FA__recovery_codes {
            get {
                return ResourceManager.GetString("Generate two-factor authentication (2FA) recovery codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generating new recovery codes does not change the keys used in authenticator apps..
        /// </summary>
        public static string Generating_new_recovery_codes_does_not_change_the_keys_used_in_authenticator_apps_ {
            get {
                return ResourceManager.GetString("Generating new recovery codes does not change the keys used in authenticator apps" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you do not complete your authenticator app configuration you may lose access to your account..
        /// </summary>
        public static string If_you_do_not_complete_your_authenticator_app_configuration_you_may_lose_access_to_your_account_ {
            get {
                return ResourceManager.GetString("If you do not complete your authenticator app configuration you may lose access t" +
                        "o your account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you lose your device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        public static string If_you_lose_your_device_and_don_t_have_the_recovery_codes_you_will_lose_access_to_your_account_ {
            get {
                return ResourceManager.GetString("If you lose your device and don\'t have the recovery codes you will lose access to" +
                        " your account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you reset your authenticator key your authenticator app will not work until you reconfigure it..
        /// </summary>
        public static string If_you_reset_your_authenticator_key_your_authenticator_app_will_not_work_until_you_reconfigure_it_ {
            get {
                return ResourceManager.GetString("If you reset your authenticator key your authenticator app will not work until yo" +
                        "u reconfigure it.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you wish to change the key used in an authenticator app you should.
        /// </summary>
        public static string If_you_wish_to_change_the_key_used_in_an_authenticator_app_you_should {
            get {
                return ResourceManager.GetString("If you wish to change the key used in an authenticator app you should", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à into your two factor authenticator app. Spaces and casing do not matter..
        /// </summary>
        public static string into_your_two_factor_authenticator_app__Spaces_and_casing_do_not_matter_ {
            get {
                return ResourceManager.GetString("into your two factor authenticator app. Spaces and casing do not matter.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid authenticator code entered for user with ID &apos;{0}&apos;..
        /// </summary>
        public static string Invalid_authenticator_code_entered_for_user_with_ID___0___ {
            get {
                return ResourceManager.GetString("Invalid authenticator code entered for user with ID \'{0}\'.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid password reset.
        /// </summary>
        public static string Invalid_password_reset {
            get {
                return ResourceManager.GetString("Invalid password reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid recovery code entered for user with ID &apos;{0}&apos;!.
        /// </summary>
        public static string Invalid_recovery_code_entered_for_user_with_ID___0___ {
            get {
                return ResourceManager.GetString("Invalid recovery code entered for user with ID \'{0}\'!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid user.
        /// </summary>
        public static string Invalid_user {
            get {
                return ResourceManager.GetString("Invalid user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Learn how to.
        /// </summary>
        public static string Learn_how_to {
            get {
                return ResourceManager.GetString("Learn how to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à link external login provider {0}.
        /// </summary>
        public static string link_external_login_provider__0_ {
            get {
                return ResourceManager.GetString("link external login provider {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locked out.
        /// </summary>
        public static string Locked_out {
            get {
                return ResourceManager.GetString("Locked out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à log in with a recovery code.
        /// </summary>
        public static string log_in_with_a_recovery_code {
            get {
                return ResourceManager.GetString("log in with a recovery code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à log-in with provider.
        /// </summary>
        public static string log_in_with_provider {
            get {
                return ResourceManager.GetString("log-in with provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage email.
        /// </summary>
        public static string Manage_email {
            get {
                return ResourceManager.GetString("Manage email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage your external logins.
        /// </summary>
        public static string Manage_your_external_logins {
            get {
                return ResourceManager.GetString("Manage your external logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New email.
        /// </summary>
        public static string New_email {
            get {
                return ResourceManager.GetString("New email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normally this would be emailed:.
        /// </summary>
        public static string Normally_this_would_be_emailed_ {
            get {
                return ResourceManager.GetString("Normally this would be emailed:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old password.
        /// </summary>
        public static string Old_password {
            get {
                return ResourceManager.GetString("Old password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Once you have scanned the QR code or input the key above, your two factor authentication app will provide you with a unique code..
        /// </summary>
        public static string Once_you_have_scanned_the_QR_code_or_input_the_key_above__your_two_factor_authentication_app_will_provide_you_with_a_unique_code_ {
            get {
                return ResourceManager.GetString("Once you have scanned the QR code or input the key above, your two factor authent" +
                        "ication app will provide you with a unique code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please check your email to confirm your account..
        /// </summary>
        public static string Please_check_your_email_to_confirm_your_account_ {
            get {
                return ResourceManager.GetString("Please check your email to confirm your account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please check your email to reset your password..
        /// </summary>
        public static string Please_check_your_email_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("Please check your email to reset your password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose your username..
        /// </summary>
        public static string Please_choose_your_username_ {
            get {
                return ResourceManager.GetString("Please choose your username.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please click here to log in!.
        /// </summary>
        public static string Please_click_here_to_log_in_ {
            get {
                return ResourceManager.GetString("Please click here to log in!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please confirm your new password..
        /// </summary>
        public static string Please_confirm_your_new_password_ {
            get {
                return ResourceManager.GetString("Please confirm your new password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please confirm your password..
        /// </summary>
        public static string Please_confirm_your_password_ {
            get {
                return ResourceManager.GetString("Please confirm your password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter an email address for this site below and click the Register button to finish logging in.
        /// </summary>
        public static string Please_enter_an_email_address_for_this_site_below_and_click_the_Register_button_to_finish_logging_in {
            get {
                return ResourceManager.GetString("Please enter an email address for this site below and click the Register button t" +
                        "o finish logging in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter new email..
        /// </summary>
        public static string Please_enter_new_email_ {
            get {
                return ResourceManager.GetString("Please enter new email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the code..
        /// </summary>
        public static string Please_enter_the_code_ {
            get {
                return ResourceManager.GetString("Please enter the code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your email.
        /// </summary>
        public static string Please_enter_your_email_ {
            get {
                return ResourceManager.GetString("Please enter your email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your new password..
        /// </summary>
        public static string Please_enter_your_new_password_ {
            get {
                return ResourceManager.GetString("Please enter your new password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your old password..
        /// </summary>
        public static string Please_enter_your_old_password_ {
            get {
                return ResourceManager.GetString("Please enter your old password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your password..
        /// </summary>
        public static string Please_enter_your_password_ {
            get {
                return ResourceManager.GetString("Please enter your password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Privacy and cookie policy have not been accepted..
        /// </summary>
        public static string Privacy_and_cookie_policy_have_not_been_accepted_ {
            get {
                return ResourceManager.GetString("Privacy and cookie policy have not been accepted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Put these codes in a safe place..
        /// </summary>
        public static string Put_these_codes_in_a_safe_place_ {
            get {
                return ResourceManager.GetString("Put these codes in a safe place.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery code verification.
        /// </summary>
        public static string Recovery_code_verification {
            get {
                return ResourceManager.GetString("Recovery code verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register as a new user.
        /// </summary>
        public static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register as a new user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register confirmation.
        /// </summary>
        public static string Register_confirmation {
            get {
                return ResourceManager.GetString("Register confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registered Providers.
        /// </summary>
        public static string Registered_Providers {
            get {
                return ResourceManager.GetString("Registered Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember this machine.
        /// </summary>
        public static string Remember_this_machine {
            get {
                return ResourceManager.GetString("Remember this machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resend.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resend email confirmation.
        /// </summary>
        public static string Resend_email_confirmation {
            get {
                return ResourceManager.GetString("Resend email confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset authenticator app.
        /// </summary>
        public static string Reset_authenticator_app {
            get {
                return ResourceManager.GetString("Reset authenticator app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset authenticator key.
        /// </summary>
        public static string Reset_authenticator_key {
            get {
                return ResourceManager.GetString("Reset authenticator key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset password.
        /// </summary>
        public static string Reset_password {
            get {
                return ResourceManager.GetString("Reset password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset password confirmation.
        /// </summary>
        public static string Reset_password_confirmation {
            get {
                return ResourceManager.GetString("Reset password confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset recovery codes.
        /// </summary>
        public static string Reset_recovery_codes {
            get {
                return ResourceManager.GetString("Reset recovery codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à reset your authenticator keys..
        /// </summary>
        public static string reset_your_authenticator_keys_ {
            get {
                return ResourceManager.GetString("reset your authenticator keys.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan the QR Code or enter this key.
        /// </summary>
        public static string Scan_the_QR_Code_or_enter_this_key {
            get {
                return ResourceManager.GetString("Scan the QR Code or enter this key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send verification email.
        /// </summary>
        public static string Send_verification_email {
            get {
                return ResourceManager.GetString("Send verification email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set up authenticator app.
        /// </summary>
        public static string Set_up_authenticator_app {
            get {
                return ResourceManager.GetString("Set up authenticator app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set your password.
        /// </summary>
        public static string Set_your_password {
            get {
                return ResourceManager.GetString("Set your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thank you for confirming your email.
        /// </summary>
        public static string Thank_you_for_confirming_your_email {
            get {
                return ResourceManager.GetString("Thank you for confirming your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thank you for confirming your email change..
        /// </summary>
        public static string Thank_you_for_confirming_your_email_change_ {
            get {
                return ResourceManager.GetString("Thank you for confirming your email change.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current browser has been forgotten. When you login again from this browser you will be prompted for your 2fa code..
        /// </summary>
        public static string The_current_browser_has_been_forgotten__When_you_login_again_from_this_browser_you_will_be_prompted_for_your_2fa_code_ {
            get {
                return ResourceManager.GetString("The current browser has been forgotten. When you login again from this browser yo" +
                        "u will be prompted for your 2fa code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The external login was added..
        /// </summary>
        public static string The_external_login_was_added_ {
            get {
                return ResourceManager.GetString("The external login was added.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password reset link is invalid..
        /// </summary>
        public static string The_password_reset_link_is_invalid_ {
            get {
                return ResourceManager.GetString("The password reset link is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This account has been locked out, please try again later..
        /// </summary>
        public static string This_account_has_been_locked_out__please_try_again_later_ {
            get {
                return ResourceManager.GetString("This account has been locked out, please try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This app does not currently have a real email sender registered, see &lt;a href=&quot;&quot;https://aka.ms/aspaccountconf&quot;&quot;&gt;these docs&lt;/a&gt; for how to configure a real email sender..
        /// </summary>
        public static string This_app_does_not_currently_have_a_real_email_sender_registered {
            get {
                return ResourceManager.GetString("This app does not currently have a real email sender registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This process disables 2FA until you verify your authenticator app..
        /// </summary>
        public static string This_process_disables_2FA_until_you_verify_your_authenticator_app_ {
            get {
                return ResourceManager.GetString("This process disables 2FA until you verify your authenticator app.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To use an authenticator app go through the following steps:.
        /// </summary>
        public static string To_use_an_authenticator_app_go_through_the_following_steps_ {
            get {
                return ResourceManager.GetString("To use an authenticator app go through the following steps:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two-factor authentication.
        /// </summary>
        public static string Two_factor_authentication {
            get {
                return ResourceManager.GetString("Two-factor authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Two-factor authentication (2FA).
        /// </summary>
        public static string Two_factor_authentication__2FA_ {
            get {
                return ResourceManager.GetString("Two-factor authentication (2FA)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to find user with Id {0}.
        /// </summary>
        public static string Unable_to_find_user_with_Id__0_ {
            get {
                return ResourceManager.GetString("Unable to find user with Id {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to load two-factor authentication user..
        /// </summary>
        public static string Unable_to_load_two_factor_authentication_user_ {
            get {
                return ResourceManager.GetString("Unable to load two-factor authentication user.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update password.
        /// </summary>
        public static string Update_password {
            get {
                return ResourceManager.GetString("Update password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use a local account to log in..
        /// </summary>
        public static string Use_a_local_account_to_log_in_ {
            get {
                return ResourceManager.GetString("Use a local account to log in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use another provider to register..
        /// </summary>
        public static string Use_another_provider_to_register_ {
            get {
                return ResourceManager.GetString("Use another provider to register.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use external provider to log in..
        /// </summary>
        public static string Use_external_provider_to_log_in_ {
            get {
                return ResourceManager.GetString("Use external provider to log in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User account locked out..
        /// </summary>
        public static string User_account_locked_out_ {
            get {
                return ResourceManager.GetString("User account locked out.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User with ID &apos;{0}&apos; account locked out..
        /// </summary>
        public static string User_with_ID___0___account_locked_out_ {
            get {
                return ResourceManager.GetString("User with ID \'{0}\' account locked out.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User with ID &apos;{0}&apos; logged in with 2fa..
        /// </summary>
        public static string User_with_ID___0___logged_in_with_2fa_ {
            get {
                return ResourceManager.GetString("User with ID \'{0}\' logged in with 2fa.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User with ID &apos;{0}&apos; logged in with a recovery code..
        /// </summary>
        public static string User_with_ID___0___logged_in_with_a_recovery_code_ {
            get {
                return ResourceManager.GetString("User with ID \'{0}\' logged in with a recovery code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verification Code.
        /// </summary>
        public static string Verification_Code {
            get {
                return ResourceManager.GetString("Verification Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verification email sent. Please check your email..
        /// </summary>
        public static string Verification_email_sent__Please_check_your_email_ {
            get {
                return ResourceManager.GetString("Verification email sent. Please check your email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You do not have a local username/password for this site..
        /// </summary>
        public static string You_do_not_have_a_local_username_password_for_this_site_ {
            get {
                return ResourceManager.GetString("You do not have a local username/password for this site.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have {0} recovery codes left..
        /// </summary>
        public static string You_have__0__recovery_codes_left_ {
            get {
                return ResourceManager.GetString("You have {0} recovery codes left.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have 1 recovery code left..
        /// </summary>
        public static string You_have_1_recovery_code_left_ {
            get {
                return ResourceManager.GetString("You have 1 recovery code left.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have generated new recovery codes..
        /// </summary>
        public static string You_have_generated_new_recovery_codes_ {
            get {
                return ResourceManager.GetString("You have generated new recovery codes.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have no recovery codes left..
        /// </summary>
        public static string You_have_no_recovery_codes_left_ {
            get {
                return ResourceManager.GetString("You have no recovery codes left.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have requested to log in with a recovery code. This login will not be remembered until you provide an authenticator app code at log in or disable 2FA and log in again..
        /// </summary>
        public static string You_have_requested_to_log_in_with_a_recovery_code__This_login_will_not_be_remembered_until_you_provide_an_authenticator_app_code_at_log_in_or_disable_2FA_and_log_in_again_ {
            get {
                return ResourceManager.GetString("You have requested to log in with a recovery code. This login will not be remembe" +
                        "red until you provide an authenticator app code at log in or disable 2FA and log" +
                        " in again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must accept the policy before you can enable two factor authentication..
        /// </summary>
        public static string You_must_accept_the_policy_before_you_can_enable_two_factor_authentication_ {
            get {
                return ResourceManager.GetString("You must accept the policy before you can enable two factor authentication.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You&apos;ve successfully authenticated with.
        /// </summary>
        public static string You_ve_successfully_authenticated_with {
            get {
                return ResourceManager.GetString("You\'ve successfully authenticated with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your account contains personal data that you have given us. This page allows you to download or delete that data..
        /// </summary>
        public static string Your_account_contains_personal_data_that_you_have_given_us__This_page_allows_you_to_download_or_delete_that_data_ {
            get {
                return ResourceManager.GetString("Your account contains personal data that you have given us. This page allows you " +
                        "to download or delete that data.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your authenticator app has been verified..
        /// </summary>
        public static string Your_authenticator_app_has_been_verified_ {
            get {
                return ResourceManager.GetString("Your authenticator app has been verified.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your authenticator app key has been reset, you will need to configure your authenticator app using the new key..
        /// </summary>
        public static string Your_authenticator_app_key_has_been_reset__you_will_need_to_configure_your_authenticator_app_using_the_new_key_ {
            get {
                return ResourceManager.GetString("Your authenticator app key has been reset, you will need to configure your authen" +
                        "ticator app using the new key.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your email is unchanged..
        /// </summary>
        public static string Your_email_is_unchanged_ {
            get {
                return ResourceManager.GetString("Your email is unchanged.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your login is protected with an authenticator app. Enter your authenticator code below.
        /// </summary>
        public static string Your_login_is_protected_with_an_authenticator_app__Enter_your_authenticator_code_below {
            get {
                return ResourceManager.GetString("Your login is protected with an authenticator app. Enter your authenticator code " +
                        "below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your password has been changed.
        /// </summary>
        public static string Your_password_has_been_changed {
            get {
                return ResourceManager.GetString("Your password has been changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your password has been reset..
        /// </summary>
        public static string Your_password_has_been_reset_ {
            get {
                return ResourceManager.GetString("Your password has been reset.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your password has been set..
        /// </summary>
        public static string Your_password_has_been_set_ {
            get {
                return ResourceManager.GetString("Your password has been set.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your profile has been updated.
        /// </summary>
        public static string Your_profile_has_been_updated {
            get {
                return ResourceManager.GetString("Your profile has been updated", resourceCulture);
            }
        }
    }
}
